<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>LocTray</RootNamespace>
    <AssemblyName>LocTray</AssemblyName>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Version>1.0.0</Version>
    <Company>LocTray</Company>
    <Product>LocTray</Product>
    <Description>Live PC performance in the system tray</Description>
  </PropertyGroup>

</Project>
